new_core_add_component(
    project_dillen_kernel
    SOURCES
        algorithm_registry.cpp
        algorithm_registry.hpp
        mechanism_change.hpp
        mechanism_command.cpp
        mechanism_command.hpp
        mechanism_definition.hpp
        mechanism_definition_registry.cpp
        mechanism_definition_registry.hpp
        mechanism_ids.cpp
        mechanism_ids.hpp
        mechanism_instance.hpp
        mechanism_instance_store.cpp
        mechanism_instance_store.hpp
        mechanism_lifecycle.cpp
        mechanism_lifecycle.hpp
        mechanism_query_snapshot.cpp
        mechanism_query_snapshot.hpp
        mechanism_scheduler.cpp
        mechanism_scheduler.hpp
        mechanism_schema.cpp
        mechanism_schema.hpp
        mechanism_schema_registry.cpp
        mechanism_schema_registry.hpp
        mechanism_transaction.cpp
        mechanism_transaction.hpp
        mechanism_value.cpp
        mechanism_value.hpp
        world_transaction.cpp
        world_transaction.hpp
        world_command_queue.cpp
        world_command_queue.hpp
        world_event.cpp
        world_event.hpp
    PUBLIC_INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}"
)

add_library(dillen::kernel ALIAS project_dillen_kernel)
